// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzll757YxmTOfW-0xjtQeivIhXQTaTkhA',
    appId: '1:519395440724:web:1e6fbe2537af7d3b99d5c1',
    messagingSenderId: '519395440724',
    projectId: 'labinfo-1def4',
    authDomain: 'labinfo-1def4.firebaseapp.com',
    storageBucket: 'labinfo-1def4.appspot.com',
    measurementId: 'G-Y67GZECBZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAuSCAiomwTs1-SWzoA1MqN3ffELaRyU',
    appId: '1:519395440724:android:d9b687a24db9227d99d5c1',
    messagingSenderId: '519395440724',
    projectId: 'labinfo-1def4',
    storageBucket: 'labinfo-1def4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSON9grekSqTa9avNSP_9ULnzjfSIH2_4',
    appId: '1:519395440724:ios:7e1dc9f9e269c3c199d5c1',
    messagingSenderId: '519395440724',
    projectId: 'labinfo-1def4',
    storageBucket: 'labinfo-1def4.appspot.com',
    iosClientId:
        '519395440724-of9mvi9ja6mlc4tc4j0cok5fiq8qd96q.apps.googleusercontent.com',
    iosBundleId: 'com.example.labinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSON9grekSqTa9avNSP_9ULnzjfSIH2_4',
    appId: '1:519395440724:ios:7e1dc9f9e269c3c199d5c1',
    messagingSenderId: '519395440724',
    projectId: 'labinfo-1def4',
    storageBucket: 'labinfo-1def4.appspot.com',
    iosClientId:
        '519395440724-of9mvi9ja6mlc4tc4j0cok5fiq8qd96q.apps.googleusercontent.com',
    iosBundleId: 'com.example.labinfo',
  );
}
